"""
Run the full donor-biographies analysis pipeline for the paper
"Collections grow by volume but diversify by exception: donor biographies in
MoMA's gift channel, 1929-2024" (Museum Management and Curatorship).

Usage:
    cd /home/jhbae/moma && python code/run_all.py

Inputs (in data/):
    Artworks_full.csv            raw MoMA collection export (step 01 input)
    processed_moma_data.csv      preprocessed analysis table (regenerated by step 01)
    tate/processed_tate_data.csv Tate cross-museum sample (steps 33, 37, 39)

Outputs go to output/ (regenerated; not tracked in git). See REPLICATION.md
for the mapping from each script to the paper's tables and figures.
"""

import os
import sys
import subprocess

CODE_DIR = os.path.dirname(os.path.abspath(__file__))

# (script, timeout_seconds). Ordered so each step's inputs are produced upstream.
STEPS = [
    ("01_data_preprocessing", 600),        # -> data/processed_moma_data.csv
    ("32_donor_exploratory_profile", 300), # -> output/table_donor_exploratory_top20.tex
    ("34_donor_biographies", 300),         # -> donor_biography_profile.csv, cumulative_*.csv
    ("35_donor_cross_comparison", 300),    # -> donor_demographic_gap.csv, six_donor_joint_counterfactual.csv
    ("36_donor_figures", 300),             # -> fig_donor_*.{eps,pdf}, fig_six_donor_jointcf.{eps,pdf}
    ("41_strong_accept_analyses", 600),    # -> fig_volume_vs_gap.{eps,pdf}, population_decorrelation.csv, catalogue_oos_*.csv
    ("40_concentration_canonical_recompute", 300),  # -> concentration_canonical_recompute.csv
    ("33_donor_exploratory_profile_tate", 300),     # Tate exploratory profile
    ("37_donor_tate_crossmuseum", 300),             # Tate cross-museum recurrence
    ("39_phase_l_tate_channel_filter", 300),        # channel-filtered Tate selection -> tate_*_v2.csv
    ("38_phase_j_verifications", 300),     # -> output/symmetric_boundary_check.tex, arithmetic checks
]


def run_step(script_name, timeout):
    print("\n" + "=" * 60)
    print(f"Running {script_name}")
    print("=" * 60)
    r = subprocess.run(
        [sys.executable, os.path.join(CODE_DIR, script_name + ".py")],
        cwd=os.path.dirname(CODE_DIR),  # project root, so data/ and output/ resolve
        timeout=timeout,
    )
    if r.returncode != 0:
        raise SystemExit(f"{script_name} failed with exit code {r.returncode}")


def main():
    for script_name, timeout in STEPS:
        run_step(script_name, timeout)
    print("\nDone. Results are in output/. The paper's \\input tables and figures")
    print("(table_donor_exploratory_top20.tex, symmetric_boundary_check.tex, fig_*) are")
    print("copied into moma_paper/output/ for the LaTeX build.")


if __name__ == "__main__":
    main()
